CREATE TABLE IF NOT EXISTS users (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name        VARCHAR(255) NOT NULL,
  email       VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id     BIGINT NOT NULL,
  name        VARCHAR(255) NOT NULL,
  description VARCHAR(100) NOT NULL,
  available   BOOLEAN NOT NULL,
  CONSTRAINT pk_item PRIMARY KEY (id),
  CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS bookings (
       id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
       user_id BIGINT NOT NULL,
       item_id BIGINT NOT NULL,
       end_of      TIMESTAMP NOT NULL,
       start_of    TIMESTAMP NOT NULL,
       status      VARCHAR(50) DEFAULT 'WAITING',
       CONSTRAINT pk_booking PRIMARY KEY (id),
       CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id),
       CONSTRAINT fk_item_id FOREIGN KEY (item_id) REFERENCES items(id)
);

