CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name        VARCHAR(255)                                        NOT NULL,
    email       VARCHAR(255)                                 UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS requests (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    description VARCHAR(255)                                        NOT NULL,
    user_id     BIGINT                                              NOT NULL,
    created     TIMESTAMP                                           NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    user_id     BIGINT                                              NOT NULL,
    request_id  BIGINT,
    name        VARCHAR(255)                                        NOT NULL,
    description VARCHAR(255)                                        NOT NULL,
    available   BOOLEAN                                             NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (request_id) REFERENCES requests (id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    item_id     BIGINT                                              NOT NULL,
    user_id     BIGINT                                              NOT NULL,
    start_of    TIMESTAMP                                           NOT NULL,
    end_of      TIMESTAMP                                           NOT NULL,
    status      VARCHAR(50)                                         NOT NULL,
    FOREIGN KEY (item_id) REFERENCES items(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    text        VARCHAR(255)                                        NOT NULL,
    author_id   BIGINT                                              NOT NULL,
    item_id     BIGINT                                              NOT NULL,
    created     TIMESTAMP                                           NOT NULL,
    FOREIGN KEY (author_id) REFERENCES users(id),
    FOREIGN KEY (item_id) REFERENCES items(id)
);